export const myStructure = (S, context) =>
  S.list()
    .title("Home")
    .items([
      S.listItem()
        .title("Home")
        .child(S.document().schemaType("home").documentId("home")),
      S.listItem()
        .title("Orte")
        .child(S.document().schemaType("orte").documentId("orte")),
      S.listItem()
        .title("Project")
        .child(S.document().schemaType("project").documentId("project")),
      S.listItem()
        .title("People")
        .child(S.document().schemaType("people").documentId("people")),
      S.listItem()
        .title("Contact")
        .child(S.document().schemaType("contact").documentId("contact")),
      S.divider(),
      S.listItem()
        .title("Videos")
        .schemaType("video")
        .child(S.documentTypeList("video").title("Videos")),
      S.divider(),
      S.listItem()
        .title("Legals")
        .child(S.document().schemaType("legals").documentId("legals")),
    ]);
